# Generated by Django 4.1.3 on 2022-11-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_board_writer_board_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
