# Generated by Django 4.1.3 on 2022-11-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_board_imgfile'),
    ]
    
    
    