# Generated by Django 4.1.3 on 2022-11-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_grouprecommend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='content',
        ),
        migrations.AddField(
            model_name='board',
            name='solimg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
