# Generated by Django 4.1.3 on 2022-11-17 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='anmswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=20, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestImage',
            fields=[
                ('test_id', models.BigAutoField(help_text='test_id', primary_key=True, serialize=False)),
                ('imgfile', models.ImageField(blank=True, null=True, upload_to='')),
                ('answer', models.IntegerField()),
                ('bigtitle', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='leveltests',
            name='test_id',
        ),
        migrations.DeleteModel(
            name='TestImages',
        ),
    ]
