# Generated by Django 4.1.3 on 2022-11-17 10:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test', '0002_anmswer_testimage_remove_leveltests_test_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='anmswer',
            new_name='answer',
        ),
    ]
