# Generated by Django 4.1.3 on 2022-11-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0003_rename_anmswer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
