# Generated by Django 4.1.3 on 2022-11-19 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test', '0007_alter_answer_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestImages',
            fields=[
                ('test_id', models.BigAutoField(help_text='test_id', primary_key=True, serialize=False)),
                ('imgfile', models.ImageField(blank=True, null=True, upload_to='')),
                ('answer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='title',
            fields=[
                ('title_id', models.IntegerField(help_text='title_id', primary_key=True, serialize=False)),
                ('big_title', models.CharField(max_length=20, null=True)),
                ('title', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, null=True)),
                ('correct', models.IntegerField()),
                ('test_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='test.testimages')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='leveltests',
            name='user',
        ),
        migrations.DeleteModel(
            name='TestImage',
        ),
        migrations.DeleteModel(
            name='answer',
        ),
        migrations.DeleteModel(
            name='LevelTests',
        ),
        migrations.AddField(
            model_name='testimages',
            name='title_id',
            field=models.ForeignKey(db_column='title_id', on_delete=django.db.models.deletion.CASCADE, to='test.title'),
        ),
    ]
