# Generated by Django 4.1.3 on 2022-11-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0008_testimages_title_total_remove_answer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='category',
            field=models.IntegerField(null=True),
        ),
    ]
